asakusafw/asakusafw-compiler

bridge-project/runtime-adapter/pom.xml
bridge-project/runtime-directio/pom.xml
bridge-project/runtime-hadoop/pom.xml
bridge-project/runtime/pom.xml
compiler-project/analyzer/pom.xml
compiler-project/api-testing/pom.xml
compiler-project/core/pom.xml
compiler-project/extension-cleanup/pom.xml
compiler-project/extension-directio/pom.xml
compiler-project/extension-test-moderator/pom.xml
compiler-project/mapreduce-testing/pom.xml
compiler-project/mapreduce/pom.xml
compiler-project/operator-project/builtin/pom.xml
compiler-project/operator-project/core/pom.xml
compiler-project/operator-project/dmdl/pom.xml
pom.xml

Note that each asakusafw artifacts is referred as provided scope, so this change may have little effect on application code.

Change referred asakusafw version to `0.7.3-hadoop2`.

---

compiler-project/core/src/main/java/com/asakusafw/lang/compiler/core/participant/JavaSourceExtensionParticipant.java
compiler-project/core/src/main/java/com/asakusafw/lang/compiler/core/util/AbstractCompositeElement.java
compiler-project/javac/src/main/java/com/asakusafw/lang/compiler/javac/AbstractJavaCompilerSupport.java
compiler-project/operator-project/core/src/test/java/com/asakusafw/lang/compiler/operator/DelegateProcessor.java
pom.xml

This PR bumps up Java version to `1.8` .
N/A.
N/A.
N/A.
@akirakw

Bump up Java version to 1.8.

---

bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/Compatibility.java
bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/directio/DirectFileInputFormat.java
bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/directio/Util.java
compiler-project/mapreduce-testing/src/main/java/com/asakusafw/lang/compiler/mapreduce/testing/InputFormatTester.java
compiler-project/mapreduce/src/test/java/com/asakusafw/lang/compiler/mapreduce/MapReduceStageEmitterTest.java

This PR fixes for upstream changes in asakusafw/asakusafw#662.
see asakusafw/asakusafw#662
N/A.
* asakusafw/asakusafw#662
@akirakw

Fix for upstream changes (`*Compatibility` was removed).

---

compiler-project/extension-windgate/src/main/java/com/asakusafw/lang/compiler/extension/windgate/WindGateConstants.java
compiler-project/extension-windgate/src/main/java/com/asakusafw/lang/compiler/extension/windgate/WindGatePortProcessor.java
compiler-project/extension-windgate/src/test/java/com/asakusafw/lang/compiler/extension/windgate/WindGatePortProcessorTest.java

This PR refactors WindGate constants.
N/A.
N/A.
N/A.
@akirakw

Refactor WindGate constants.

---

vanilla/runtime/core/pom.xml

This PR fixes pom.xml.
`vanilla/runtime/core/pom.xml` includes a duplicated dependency.
N/A.
N/A.
@akirakw

Fix pom.xml.

---

compiler-project/test-adapter/src/main/java/com/asakusafw/lang/compiler/testdriver/adapter/CompilerConfigurationAdapter.java
compiler-project/test-adapter/src/main/java/com/asakusafw/lang/compiler/testdriver/adapter/CompilerProfileInitializer.java
compiler-project/test-adapter/src/main/java/com/asakusafw/lang/compiler/testdriver/adapter/CompilerSessionAdapter.java
compiler-project/test-adapter/src/main/java/com/asakusafw/lang/compiler/testdriver/adapter/CompilerToolkitAdapter.java
vanilla/testkit/adapter/pom.xml
vanilla/testkit/adapter/src/main/java/com/asakusafw/vanilla/testkit/adapter/VanillaCompilerProfileInitializer.java

This PR fixes for upstream changes (asaksuafw/asakusafw#688).
see asakusafw/asakusafw#688.
This also enables Asakusa Vanilla use `*Tester.configure()`.
* asakusafw/asakusafw#688
@akirakw

Fix for upstream changes.

---

compiler-project/common-testing/src/main/java/com/asakusafw/lang/compiler/common/testing/FileEditor.java
compiler-project/javac/src/main/java/com/asakusafw/lang/compiler/javac/BasicJavaCompilerSupport.java
compiler-project/mapreduce-testing/src/main/java/com/asakusafw/lang/compiler/mapreduce/testing/mock/WritableModelInput.java
compiler-project/optimizer/pom.xml
compiler-project/optimizer/src/conf/findbugs/exclude.xml
compiler-project/optimizer/src/main/java/com/asakusafw/lang/compiler/optimizer/OperatorRewriters.java
compiler-project/packaging/src/main/java/com/asakusafw/lang/compiler/packaging/FileRepository.java
compiler-project/packaging/src/main/java/com/asakusafw/lang/compiler/packaging/ResourceUtil.java
compiler-project/plan/src/main/java/com/asakusafw/lang/compiler/planning/PlanBuilder.java
compiler-project/tester/src/main/java/com/asakusafw/lang/compiler/tester/executor/TaskExecutors.java
dag/runtime/jdbc/src/test/java/com/asakusafw/dag/runtime/jdbc/basic/BasicConnectionPoolTest.java
dag/runtime/jdbc/src/test/java/com/asakusafw/dag/runtime/jdbc/basic/SimpleConnectionPoolTest.java
pom.xml

This PR bumps up artifact versions dependencies and Maven plug-ins.
N/A.
We also revises code style for FindBugs `3.0.{0->4}`.
N/A.
@akirakw

Bump up dependency versions.

---

vanilla/compiler/core/src/main/java/com/asakusafw/vanilla/compiler/core/VanillaJobflowProcessor.java
vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/engine/BasicVertexScheduler.java
vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/BasicBufferPool.java

This PR fixes code style of Asakusa Vanilla (`./vanilla`).
N/A.
N/A.
N/A.
N/A.

Fix code style.

---

compiler-project/core/src/main/java/com/asakusafw/lang/compiler/core/basic/BasicBatchCompiler.java
compiler-project/core/src/main/java/com/asakusafw/lang/compiler/core/basic/BasicJobflowCompiler.java

This PR enables to show the context flow ID if compiling the target jobflow was failed.
N/A.
This will insert an `ERROR` level log before actual error messages, which log record will show the context batch ID and flow ID.
N/A.
@akirakw

Show the context flow ID on compile error.

---

README.md

This PR adds a link to Asakusa on M<sup>3</sup>BP project into README file.
The above project has become a direct sub-project of this since asakusafw/asakusafw-m3bp#84.
N/A.
* asakusafw/asakusafw-m3bp#84
@akirakw

Add a link to subproject into README file.

---

compiler-project/extension-directio/pom.xml
compiler-project/extension-directio/src/test/java/com/asakusafw/lang/compiler/extension/directio/info/DirectFileIoAttributeCollectorTest.java
compiler-project/extension-info/pom.xml
compiler-project/extension-info/src/test/java/com/asakusafw/lang/compiler/extension/info/ParameterListAttributeCollectorTest.java
info/api/pom.xml
info/api/src/test/java/com/asakusafw/lang/info/api/MockAttributeCollectorContext.java
info/directio/pom.xml
info/directio/src/main/java/com/asakusafw/lang/info/directio/DirectFileInputInfo.java
info/directio/src/main/java/com/asakusafw/lang/info/directio/DirectFileIoAttribute.java
info/directio/src/main/java/com/asakusafw/lang/info/directio/DirectFileOutputInfo.java
info/directio/src/main/java/com/asakusafw/lang/info/directio/DirectFilePortInfo.java
info/directio/src/test/java/com/asakusafw/lang/info/directio/DirectFileInputInfoTest.java
info/directio/src/test/java/com/asakusafw/lang/info/directio/DirectFileIoAttributeTest.java
info/directio/src/test/java/com/asakusafw/lang/info/directio/DirectFileOutputInfoTest.java
info/model/pom.xml
info/model/src/main/java/com/asakusafw/lang/info/BatchInfo.java
info/model/src/main/java/com/asakusafw/lang/info/JobflowInfo.java
info/model/src/main/java/com/asakusafw/lang/info/ParameterInfo.java
info/model/src/main/java/com/asakusafw/lang/info/ParameterListAttribute.java
info/model/src/test/java/com/asakusafw/lang/info/BatchInfoTest.java
info/model/src/test/java/com/asakusafw/lang/info/InfoSerDe.java
info/model/src/test/java/com/asakusafw/lang/info/JobflowInfoTest.java
info/model/src/test/java/com/asakusafw/lang/info/MockAttribute.java
info/model/src/test/java/com/asakusafw/lang/info/ParameterInfoTest.java
info/model/src/test/java/com/asakusafw/lang/info/ParameterListAttributeTest.java

This PR adds unit tests about #113.
N/A.
N/A.
* #113

Add tests about DSL information collectors.

---

dag/compiler/flow/src/main/java/com/asakusafw/dag/compiler/flow/DirectLauncherScriptGenerator.java
dag/compiler/flow/src/main/resources/com/asakusafw/dag/compiler/flow/direct.sh.template
vanilla/compiler/core/src/main/java/com/asakusafw/vanilla/compiler/core/VanillaDirectBatchProcessor.java

This PR just refactors #117.
N/A.
N/A.
* #117

Refactoring.

---

dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/skeleton/EdgeOutputAdapter.java
dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/skeleton/EdgeOutputHandler.java
dag/runtime/runtime/src/test/java/com/asakusafw/dag/runtime/skeleton/EdgeOutputAdapterTest.java

This PR introduces a new pre-aggregation strategy for Asakusa {on M3BP, Vanilla}, and each strategy is now selectable.
The latest implementation, pre-aggregation always works on Java `HashMap`. It may occur extra GC operations in several cases.
We introduced the following new engine configuration:
* `com.asakusafw.dag.output.aggregate.strategy`
* available values:
* `MAP` - using Java HashMap
* `HASH` - using hash based cache table
* `DISABLED` - disable pre-aggregation
* default: `MAP`
* `com.asakusafw.dag.output.aggregate.window.size`
* the aggregation window size (the number of entries)
* default: `256`
Each strategy has the following properties:
* `MAP`
* performs like "fully associative cache" - never conflict aggregation keys
* flush **ALL** objects if the aggregation window was …

Introduce a new pre-aggregation strategy.

---

dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/table/BasicDataTable.java

"Key element" itself is not "type."
N/A
N/A
N/A
N/A

Fix the kind mismatch between "element" and "type"

---

dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/table/BasicDataTable.java

The word "never" must be following the word "must." 
N/A
N/A
N/A
N/A

Fix the words order

---

vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/LaunchUtil.java
vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/VanillaDirect.java
vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/VanillaLauncher.java

This PR just refactoring about Asakusa on Vanilla launcher.
Asakusa on Vanilla have had duplicated parts with Asakusa on M3BP.
We moved the common part in `VanillaLauncher` into a new utility class.
N/A.

Refactoring launching Vanilla.

---

gradle/build.gradle
gradle/src/main/groovy/com/asakusafw/lang/gradle/plugins/internal/AsakusaLangBaseExtension.groovy
gradle/src/main/groovy/com/asakusafw/lang/gradle/plugins/internal/AsakusaLangBasePlugin.groovy
pom.xml
vanilla/gradle/build.gradle
vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaBaseExtension.groovy
vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaBasePlugin.groovy

This PR removes asakusafw-sdk.version that is no longer use in this project.
See: asakusafw/asakusafw#738
N/A.
asakusafw/asakusafw#738

Remove asakusafw-sdk.version

---

compiler-project/core/pom.xml
compiler-project/core/src/main/java/com/asakusafw/lang/compiler/core/participant/ImplicitParameterListPartitcipant.java
compiler-project/core/src/main/resources/META-INF/services/com.asakusafw.lang.compiler.core.CompilerParticipant
compiler-project/extension-info/pom.xml
compiler-project/extension-info/src/main/java/com/asakusafw/lang/compiler/extension/info/AttributeCollectorContextAdapter.java
compiler-project/extension-info/src/main/java/com/asakusafw/lang/compiler/extension/info/ParameterListAttributeCollector.java
compiler-project/extension-workflow/pom.xml
compiler-project/extension-workflow/src/main/java/com/asakusafw/lang/compiler/extension/workflow/WorkflowBatchProcessor.java
compiler-project/info/src/main/java/com/asakusafw/lang/compiler/info/AttributeCollector.java
compiler-project/parameter/.gitignore
compiler-project/parameter/pom.xml
compiler-project/parameter/src/main/java/com/asakusafw/lang/compiler/parameter/ImplicitParameterList.java
compiler-project/parameter/src/main/java/com/asakusafw/lang/compiler/parameter/package-info.java
compiler-project/pom.xml
compiler-project/test-adapter/src/main/java/com/asakusafw/lang/compiler/testdriver/adapter/CompilerSessionAdapter.java
gradle/src/main/groovy/com/asakusafw/lang/gradle/plugins/internal/AsakusaLangSdkPlugin.groovy
integration/src/integration-test/data/vanilla/build.gradle
integration/src/integration-test/java/com/asakusafw/integration/lang/PortalTest.java
integration/src/integration-test/java/com/asakusafw/integration/lang/VanillaTest.java
vanilla/testkit/adapter/src/main/java/com/asakusafw/vanilla/testkit/adapter/VanillaTaskAttributeCollector.java
vanilla/testkit/inprocess/src/main/java/com/asakusafw/vanilla/testkit/inprocess/InProcessVanillaTaskExecutor.java

This PR revise for `bin/asakusafw.sh` command introduced in asakusafw/asakusafw#747. 
See asakusafw/asakusafw#747.
This includes the following changes:
* always generates workflow information (`etc/workflow.json`) even if `asakusafw.sdk.incubating false`
* provides batch parameter information to `asakusafw.sh run`
* asakusafw/asakusafw#747

Revise for `asakusafw.sh` command.

---

integration/src/integration-test/java/com/asakusafw/integration/lang/PortalTest.java
integration/src/integration-test/java/com/asakusafw/integration/lang/VanillaTest.java

This PR refactors common framework command name in integration test.
N/A.
N/A.
* asakusafw/asakusafw#748

Refactor command names in integration test.

---

integration/src/integration-test/java/com/asakusafw/integration/lang/VanillaTest.java

This PR fixes integration test for Windows platform.
See asakusafw/asakusafw#755, #157.
This fix just ignores test cases about YAESS.
* asakusafw/asakusafw#755
* #157

Fix integration test for Windows.

---

.mvn/wrapper/maven-wrapper.properties
pom.xml

This PR bumps Maven version defines Maven Wrapper.
This PR also bumps some Maven plugin version.
N/A.
N/A.
- asakusafw/asakusafw#763

Bump up Maven Wrapper and Maven Plugins

---

gradle/build.gradle
integration/build.gradle
pom.xml
vanilla/gradle/build.gradle

This PR bumps up dependency library versions.
N/A.
N/A.
N/A.

Bump up dependency library versions

---

integration/src/integration-test/data/vanilla/build.gradle
integration/src/integration-test/java/com/asakusafw/integration/lang/PortalTest.java

This PR fixes integration test for changes in asakusafw/asakusafw#775.
N/A.
This also includes a new integration test of `asakusa generate ddl` and its sub command.
* asakusafw/asakusafw#774
* asakusafw/asakusafw#775

Fix integration test for upstream (rename asakusa commands).

---

gradle/gradle/wrapper/gradle-wrapper.properties
integration/gradle/wrapper/gradle-wrapper.properties
vanilla/gradle/gradle/wrapper/gradle-wrapper.properties
vanilla/gradle/src/test/groovy/com/asakusafw/vanilla/gradle/plugins/AsakusaUpgradeTest.groovy

This PR bump up the Gradle version to 4.2
N/A.
N/A.
N/A.

Bump Gradle version to 4.2

---

compiler-project/plan/src/main/java/com/asakusafw/lang/compiler/planning/Planning.java
dag/compiler/plan/src/test/java/com/asakusafw/dag/compiler/planner/DagPlanningTest.java

This PR is continuation of #183, which resolves more cases of cyclic broadcast dependencies.
This PR revises cyclic broadcast dependencies resolution in #183, then this will cover more cases and removes more redundancies in run time.
N/A.
* #183

Reduce more cyclic broadcast dependencies.

---

compiler-project/plan/src/main/java/com/asakusafw/lang/compiler/planning/Planning.java
dag/compiler/plan/src/test/java/com/asakusafw/dag/compiler/planner/DagPlanningTest.java

This PR is continuation of #183 and #184.
See #183.
N/A.
* #183
* #184

Reduce more cyclic broadcast dependencies, revisited.

---

compiler-project/test-adapter/src/main/java/com/asakusafw/lang/compiler/testdriver/adapter/CompilerSessionAdapter.java

This PR enables that test driver shows diagnostics information when testee has compile errors.
In the latest implementation, test drivers cannot provide detail information of compilation warnings and errors.
N/A.
N/A.

Test drivers must show diagnostics when compilation was failed.

---

pom.xml

This PR bumps up Jackson to the latest version.
N/A.
N/A.
N/A.

Bump up Jackson version

---

dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/data/HeapListBuilder.java
dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/data/SpillListBuilder.java

Added IndexOutOfBoundsException message

HeapListBuilder: Added IndexOutOfBoundsException message
