bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/directio/DirectFileInputFormat.java, bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/directio/DirectFileInputSplit.java, bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/directio/Util.java, bridge-project/runtime-hadoop/src/test/java/com/asakusafw/bridge/hadoop/directio/DirectFileInputFormatTest.java, compiler-project/mapreduce-testing/src/main/java/com/asakusafw/lang/compiler/mapreduce/testing/mock/MockData.java
This will fix Direct I/O input filter on Spark.
=> Put batch arguments into Direct I/O input splits.

compiler-project/analyzer/src/main/java/com/asakusafw/lang/compiler/analyzer/builtin/BuiltInOperatorRewriter.java, compiler-project/analyzer/src/main/java/com/asakusafw/lang/compiler/analyzer/builtin/EmptyMasterJoinRemover.java, compiler-project/analyzer/src/main/java/com/asakusafw/lang/compiler/analyzer/util/MasterJoinOperatorUtil.java, compiler-project/analyzer/src/test/java/com/asakusafw/lang/compiler/analyzer/builtin/BuiltInOperatorRewriterTest.java, compiler-project/analyzer/src/test/java/com/asakusafw/lang/compiler/analyzer/builtin/EmptyMasterJoinRemoverTest.java
* `operator.masterjoin.remove.empty.master`
* remove master-join like operator if master input is empty
* default: `false` (experimental feature)
* `operator.masterjoin.remove.empty.transaction`
* remove master-join like operator if transaction input is empty
* default: `false` (experimantal feature)
=> Add optimizations for join with empty inputs.

.gitignore
While I was reviewing and trying to hack the code with IntelliJ, `.iml` files and `.idea` directory generated by IntelliJ bothered me a lot when I'm trying to run some git commands. This pull request makes git ignore all such generated files.
=> Add files generated by IntelliJ to .gitignore

compiler-project/analyzer/src/main/java/com/asakusafw/lang/compiler/analyzer/Info.java, compiler-project/analyzer/src/main/resources/META-INF/services/com.asakusafw.lang.compiler.api.ExtensionInfo, compiler-project/api/src/main/java/com/asakusafw/lang/compiler/api/ExtensionInfo.java, compiler-project/core/src/main/java/com/asakusafw/lang/compiler/core/participant/BuildLogParticipant.java, compiler-project/test-adapter/src/main/java/com/asakusafw/lang/compiler/testdriver/adapter/Info.java, compiler-project/test-adapter/src/main/resources/META-INF/services/com.asakusafw.lang.compiler.api.ExtensionInfo
This commit enables to record more artifact versions into the compiler's build logs.
The compiler's build log only includes information about terminal extensions, and indirect modules cannot appear on it (e.g. `asakusafw-dag`).
This commit introduces `com.asakusafw.lang.compiler.api.ExtensionInfo`. Once register implementations into `META-INF/services`, then the compiler will collect and put them onto build logs.
N/A.
@akirakw
=> Enable to record more artifact versions into build logs.

compiler-project/extension-hive/src/main/java/com/asakusafw/lang/compiler/extension/hive/HiveSchemaAggregatorProcessor.java, compiler-project/extension-hive/src/main/java/com/asakusafw/lang/compiler/extension/hive/HiveSchemaCollectorProcessor.java, compiler-project/extension-hive/src/main/java/com/asakusafw/lang/compiler/extension/hive/Util.java
This commit fixes library checking routine in #60.
#60 includes hive libraries checking mechanism is available but it does not work.
Fixed to continue collecting Hive schema info only if the related classes are available.
* #60
N/A.
=> Fix checking if hive libraries are available.

compiler-project/analyzer/src/main/java/com/asakusafw/lang/compiler/analyzer/builtin/EmptyMasterJoinRemover.java, compiler-project/optimizer/src/main/java/com/asakusafw/lang/compiler/optimizer/OptimizerContext.java, compiler-project/optimizer/src/main/java/com/asakusafw/lang/compiler/optimizer/OptimizerToolkit.java, compiler-project/optimizer/src/main/java/com/asakusafw/lang/compiler/optimizer/adapter/ForwardingOptimizerContext.java, compiler-project/optimizer/src/main/java/com/asakusafw/lang/compiler/optimizer/adapter/OptimizerContextAdapter.java, compiler-project/optimizer/src/main/java/com/asakusafw/lang/compiler/optimizer/basic/BasicOptimizerToolkit.java, compiler-project/optimizer/src/test/java/com/asakusafw/lang/compiler/optimizer/testing/MockOptimizerContext.java
This commit includes `OptimizerToolkit` interface for optimization mechanism, to implement planner dependent operations.
It seems that #54 does not work well. It requires that input ports does not have any upstream ports, but the current planner puts some marker operators into all empty ports to later planning operations.
We introduce `OptimizerToolkit` interface. It provides common interface of some optimization operation over differences on each runtime platform and planning mechanism. Note that, this patch will not fix the problem, and implementations of `OptimizerToolkit` are required for each platform.
#54
@akirakw
=> Add OptimizerToolkit to implement planner dependent operations.

compiler-project/analyzer/src/main/java/com/asakusafw/lang/compiler/analyzer/FlowGraphAnalyzer.java, compiler-project/api/src/main/java/com/asakusafw/lang/compiler/api/reference/ExternalOutputReference.java, compiler-project/extension-directio/src/main/java/com/asakusafw/lang/compiler/extension/directio/DirectFileIoPortProcessor.java, compiler-project/extension-externalio/src/main/java/com/asakusafw/lang/compiler/extension/externalio/AbstractExternalPortProcessor.java, compiler-project/extension-windgate/src/main/java/com/asakusafw/lang/compiler/extension/windgate/WindGatePortProcessor.java, compiler-project/model/src/main/java/com/asakusafw/lang/compiler/model/graph/ExternalOutput.java, compiler-project/model/src/main/java/com/asakusafw/lang/compiler/model/info/ExternalOutputInfo.java
This commit introduces the "generator constraint" for  external outputs.
It constraint prevents dead-flow elision optimization even if the operator does not have any upstream sources.
When external outputs have no upstream sources, they will be removed by dead-flow elision optimization. But some of external outputs may work even if they don't have any upstream sources (e.g. truncate tables, remove files, ...). It optimizations may change equivalence of operator graph semantics.
`ExternalPortIoProcessor` now can tell whether the target external output should have the generator constraint or not. And the subsequent execution planning engines will suppress the dead-flow elision optimization if it is a generator.
* #54
* asakusafw/asakusafw#628
N/A.
=> Enable generator constraints for external outputs.

bridge-project/runtime-adapter/pom.xml, bridge-project/runtime-directio/pom.xml, bridge-project/runtime-hadoop/pom.xml, bridge-project/runtime/pom.xml, compiler-project/analyzer/pom.xml, compiler-project/api-testing/pom.xml, compiler-project/cli/pom.xml, compiler-project/core/pom.xml, compiler-project/extension-cleanup/pom.xml, compiler-project/extension-directio/pom.xml, compiler-project/extension-externalio/pom.xml, compiler-project/extension-hive/pom.xml, compiler-project/extension-test-moderator/pom.xml, compiler-project/extension-trace/pom.xml, compiler-project/extension-windgate/pom.xml, compiler-project/extension-yaess/pom.xml, compiler-project/internalio/pom.xml, compiler-project/mapreduce-testing/pom.xml, compiler-project/mapreduce/pom.xml, compiler-project/operator-project/builtin/pom.xml, compiler-project/operator-project/core/pom.xml, compiler-project/operator-project/dmdl/pom.xml, compiler-project/operator-project/vocabulary/pom.xml, compiler-project/optimizer/pom.xml, compiler-project/plan/pom.xml, compiler-project/test-adapter/pom.xml, compiler-project/tester/pom.xml, pom.xml
This commit expands `${asakusafw.groupId}` into `com.asakusafw` in each `pom.xml`.
It may decrease readability of `pom.xml`, and the group ID will not have never been substituted with another one. 
N/A.
N/A.
@akirakw
=> Expand `${asakusafw.groupId}`.

pom.xml
This commit removes unused findbugs exclusion file in pom.xml.
It seems that the findbugs exclusion file defined in `asakusafw/build-tools` does not have any effects for this project.
N/A.
N/A.
@akirakw
=> Remove unused findbugs exclusion file.

bridge-project/runtime/src/main/java/com/asakusafw/bridge/broker/ResourceBroker.java, bridge-project/runtime/src/main/java/com/asakusafw/bridge/broker/ResourceSessionEntity.java, bridge-project/runtime/src/test/java/com/asakusafw/bridge/broker/ResourceBrokerTest.java
This PR introduces `ResourceBroker.schedule()` that enables finalizing resources when resource sessions are closed.
This enhancement is for a new cache mechanism for framework APIs (it is not implemented in this PR). Finalizing ANY resources enables to dispose them easily and safely.
N/A.
N/A.
N/A.
=> Add `ResourceBroker.schedule()` to registering session shutdown hooks.

bridge-project/runtime/src/main/java/com/asakusafw/bridge/api/BatchContext.java, bridge-project/runtime/src/main/java/com/asakusafw/bridge/api/ReportAdapter.java, bridge-project/runtime/src/main/java/com/asakusafw/bridge/broker/ResourceCacheStorage.java
This PR introduces `ResourceCacheStorage` to cache framework API resources.
Each cache storage is thread local, so that executers can obtain cached resources without rendezvous on `ResourceBroker`.
The current `ResourceBroker` implementation requires synchronization when detecting the current resource session. This may slow simultaneous executions in multi-core environments.
This introduces a utility class `ResourceCacheStorage` which enables to keep a cache value without rendezvous over the `ResourceBroker`.  Finally the cached values will be automatically disposed via `ResourceBroker.schedule()`.
* #66 
@akirakw
=> Add ResourceCacheStorage to cache framework API resources.

bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/directio/DirectFileInputFormat.java
This PR revises error messages when Direct I/O input does not exist.
This feature is an implementation of asakusafw/asakusafw#632 for platforms which use the compiler features in this repository.
Please see asakusafw/asakusafw#632.
* asakusafw/asakusafw#632
N/A.
=> Revise error message on Direct I/O input missing.

compiler-project/extension-directio/src/main/java/com/asakusafw/lang/compiler/extension/directio/DirectFileIoConstants.java, compiler-project/extension-directio/src/main/java/com/asakusafw/lang/compiler/extension/directio/DirectFileIoModels.java, compiler-project/extension-directio/src/main/java/com/asakusafw/lang/compiler/extension/directio/DirectFileIoPortProcessor.java, compiler-project/extension-hive/src/main/java/com/asakusafw/lang/compiler/extension/hive/HiveSchemaCollectorProcessor.java
This PR introduces `DirectFileIoModels` to use internal compiler models directly. 
Some features directly use internal compiler models of Direct file I/O via too low level compiler API. This PR will introduce a better abstraction for them.
N/A.
N/A.
@ueshin
=> Introduce `DirectFileIoModels` to use compiler model directly.

compiler-project/analyzer/src/main/java/com/asakusafw/lang/compiler/analyzer/FlowGraphAnalyzer.java
This PR fixes to collect annotation parameters in FlowDescription constructor.
This may cause incorrect compile output when specifies same `name` attribute to `@Import` or `@Export` in flow constructor.
N/A.
N/A.
@ashigeru
=> Fix to collect annotation param on FlowDescription

vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaBasePlugin.groovy, vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaSdkBasePlugin.groovy, vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaSdkPlugin.groovy, vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaTestkit.groovy, vanilla/gradle/src/test/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaSdkPluginTest.groovy
This PR fixes for changes in asakusafw/asakusafw-sdk#109, which has been introduced `asakusafw.sdk.*` convention into Asakusa SDK Gradle plugin.
see asakusafw/asakusafw-sdk#109.
The following convention property is also now available:
* `asakusafw.vanilla.version`
* Asakusa Vanilla libraries version.
see asakusafw/asakusafw-sdk#109.
@akirakw
=> Support `asakusafw.sdk.*` convention on Gradle.

vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaOrganizerPlugin.groovy, vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaSdkBasePlugin.groovy, vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaSdkPlugin.groovy, vanilla/gradle/src/test/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaOrganizerPluginTest.groovy
This PR fixes for upstream changes in asakusafw/asakusafw-sdk#111, which has made `*.asakusafwVersion` properties deprecated.
see asakusafw/asakusafw-sdk#111.
The following convention properties are also now available:
* `asakusafwOrganizer.vanilla.version`
* Asakusa Vanilla libraries version.
* `asakusafwOrganizer.profiles.<profile-name>.vanilla.version`
* Asakusa Vanilla libraries version.
* asakusafw/asakusafw-sdk#111
@akirakw
=> Avoid using deprecated asakusafwVersion properties in Gradle plug-ins

vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaSdkPlugin.groovy
This PR fixes duplicate version outputs when executing `asakusaVersion` task with `asakusa-vanilla` Gradle Plugin.
This is caused by duplication of asakusaVersion extension in AsakusaVanillaSdkPlugin.groovy and AsakusaVanillaBasePlugin.groovy.
This PR removes extendVersionsTask from AsakusaVanillaSdkPlugin.
N/A.
@ashigeru
=> Fix duplicate asakusaVersion output

vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaBasePlugin.groovy
This PR replaces `Task.leftShift()` with `Task.doLast()` in Gradle plug-ins (`./vanilla/gradle`).
`Task.leftShift()` will have become deprecated from Gradle `3.2`.
N/A.
N/A.
@akirakw
=> Remove `Task.leftShift()` in Gradle plug-ins.

dag/compiler/builtin/src/main/java/com/asakusafw/dag/compiler/builtin/ConvertOperatorGenerator.java, dag/compiler/builtin/src/test/java/com/asakusafw/dag/compiler/builtin/ConvertOperatorGeneratorTest.java
This PR fixes `@Convert` operator behavior.
The latest implementation, `Convert.converted` will return wrong data when a succeeding operators of `Convert.original` modifies its input object.
N/A.
N/A.
@akirakw
=> Fix convert operator behavior.

compiler-project/analyzer/src/main/java/com/asakusafw/lang/compiler/analyzer/util/ProjectionOperatorUtil.java
This PR revises error messages about projective operators. 
The latest implementation only shows operator kind (one of `project`, `extend`, or `restructure`) when mapping contains some wrong properties.
This now shows `[operator-kind]{[source-type]=>[target-type]}` when mapping was failed.
N/A.
@akirakw
=> Revise error messages about projective operators.

vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaOrganizerPlugin.groovy, vanilla/gradle/src/test/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaOrganizerPluginTest.groovy
This PR disables building Asakusa vanilla apps when Gradle `assemble` task was invoked in default.
N/A.
To enable vanilla apps in `assemble`, please enable it explicitly:
```gradle
asakusafwOrganizer.vanilla.enabled true
```
N/A.
@akirakw
=> assemble task should not build vanilla apps in default.

dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/skeleton/CoGroupInputAdapter.java
This PR enables to configure window size of `InputBuffer.ESCAPE`.
The configuration did not work well, and only can prevent from using `FileMapListBuffer`. Note that, the configuration is not documented and only for internal use.
* `com.asakusafw.dag.input.file.window.size`
* the on-heap window size (in number of objects) for `InputBuffer.ESCAPE`
* or `InputBuffer.ESCAPE` is disabled if `<= 0`
* default: `256`
N/A.
@akirakw
=> Enable to configure window size of `InputBuffer.ESCAPE`.

vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/util/Buffers.java
This PR enables Asakusa Vanilla to allocate buffers on the Java heap, instead of native area.
N/A.
* `com.asakusafw.vanilla.buffer.heap` (system property)
* allocates buffers on the Java heap instead of native area
* available arguments:
* `true` - allocate to Java heap (with backing `byte[]`)
* `false` - allocate as direct byte buffer
* default: `false` (allocate as direct byte buffer)
N/A.
@akirakw
=> Vanilla now can allocate buffers on the Java heap.

dag/compiler/codegen/src/main/java/com/asakusafw/dag/compiler/codegen/CoGroupInputAdapterGenerator.java, dag/compiler/codegen/src/test/java/com/asakusafw/dag/compiler/codegen/CoGroupInputAdapterGeneratorTest.java, dag/compiler/flow/src/main/java/com/asakusafw/dag/compiler/flow/DataFlowGenerator.java, dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/data/DataAdapter.java, dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/data/HeapListBuilder.java, dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/data/ListBuilder.java, dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/data/SpillListBuilder.java, dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/data/package-info.java, dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/io/BasicDataAdapter.java, dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/skeleton/CoGroupInputAdapter.java, dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/skeleton/CoGroupInputHandler.java, dag/runtime/runtime/src/test/java/com/asakusafw/dag/runtime/data/HeapListBuilderTest.java, dag/runtime/runtime/src/test/java/com/asakusafw/dag/runtime/data/IntOptionAdapter.java, dag/runtime/runtime/src/test/java/com/asakusafw/dag/runtime/data/SpillListBuilderTest.java
This PR introduces new implementations of co-group like operator input buffer.
The latest implementation, we use `ListBuffer` family for the inputs, which includes:
* `ArrayListBuffer` - using backing array
* `FileMapListBuffer` - using backing file
The new implementation, we introduce `ListBuilder` family, which includes:
* `HeapListBuffer` - using backing array, which will replace `ArrayListBuffer`
* `SpillListBuffer` - using backing file, which will replace `FileMapListBuffer`
We especially improve performance of `SpillListBuffer` by using NIO (direct `ByteBuffer` and `FileChannel`), whereas the old implementation has used `RandomAccessFile` with byte array buffers.
Currently, this feature is available only for Asakusa {on M3BP, Vanilla}.
* #97 
@akirakw
=> Rewrite input list buffers of co-group like operators.

compiler-project/analyzer/src/main/java/com/asakusafw/lang/compiler/analyzer/FlowGraphAnalyzer.java, compiler-project/analyzer/src/main/java/com/asakusafw/lang/compiler/analyzer/builtin/CoGroupKindOperatorClassifier.java, compiler-project/analyzer/src/main/java/com/asakusafw/lang/compiler/analyzer/util/GroupOperatorUtil.java, compiler-project/analyzer/src/test/java/com/asakusafw/lang/compiler/analyzer/FlowGraphAnalyzerTest.java, compiler-project/analyzer/src/test/java/com/asakusafw/lang/compiler/analyzer/builtin/BuiltInOperatorClassifierTest.java, compiler-project/analyzer/src/test/java/com/asakusafw/lang/compiler/analyzer/util/GroupOperatorUtilTest.java, compiler-project/analyzer/src/test/java/com/asakusafw/lang/compiler/analyzer/util/LoggingOperatorUtilTest.java, compiler-project/inspection/src/main/java/com/asakusafw/lang/compiler/inspection/DslDriver.java, compiler-project/model/src/main/java/com/asakusafw/lang/compiler/model/graph/AttributeMap.java, compiler-project/model/src/main/java/com/asakusafw/lang/compiler/model/graph/Operator.java, compiler-project/model/src/main/java/com/asakusafw/lang/compiler/model/graph/OperatorInput.java, compiler-project/model/src/main/java/com/asakusafw/lang/compiler/model/graph/OperatorOutput.java, compiler-project/model/src/main/java/com/asakusafw/lang/compiler/model/graph/OperatorPort.java, compiler-project/optimizer/src/main/java/com/asakusafw/lang/compiler/optimizer/basic/OperatorClass.java, compiler-project/plan/src/main/java/com/asakusafw/lang/compiler/planning/Planning.java, dag/compiler/builtin/src/main/java/com/asakusafw/dag/compiler/builtin/CoGroupOperatorGenerator.java, dag/compiler/builtin/src/main/java/com/asakusafw/dag/compiler/builtin/Util.java, dag/compiler/builtin/src/test/java/com/asakusafw/dag/compiler/builtin/CoGroupOperatorGeneratorTest.java, dag/compiler/model/src/main/java/com/asakusafw/dag/compiler/model/plan/InputSpec.java, dag/compiler/plan/src/main/java/com/asakusafw/dag/compiler/planner/SubPlanAnalyzer.java, dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/adapter/CoGroupOperation.java, dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/skeleton/CoGroupOperationUtil.java
This PR enables `@Once` and `@Spill` for co-group inputs in Asakusa on M3BP and Asakusa Vanilla.
see asakusafw/asakusafw#695.
This PR includes the following enhancements:
* the compiler facilities now can handle custom attributes on operator inputs/outputs
* operator graph models
* flow DSL analyzer
* inspection tools
* introduced `GroupOperatorUtil` to obtain `BufferType` of co-group like operator inputs
* enable `@Once` and `@Spill` annotations in Asakusa on M3BP and Asakusa Vanilla
* asakusafw/asakusafw#695
@akirakw : this may fail until the related PR was merged
=> Enable `@Once` and `@Spill` for co-group inputs.

dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/data/SpillListBuilder.java, dag/runtime/runtime/src/test/java/com/asakusafw/dag/runtime/data/SpillListBuilderTest.java, utils/buffer/src/main/java/com/asakusafw/lang/utils/buffer/nio/ResizableNioDataBuffer.java
This PR reduces memory usage of `@Spill` in Asakusa on M3BP and Asakusa Vanilla.
The latest implementation of `SpillListBuffer` sometimes requires large ser/de buffer. It grows up to `[buffer page size] = [the number of objects should be cached on Java heap] * [object serialization size in bytes]`. In addition, building a list will be failed if the page size becomes `>=2GB`. This is addressing limit of Java `ByteBuffer`.
This implementation will flush if the serialization size of each object was larger than the threshold (`bufferSoftLimit`). Clients can change this value by setting `com.asakusafw.dag.input.file.buffer.size` in individual engine configurations (internal).
* #101 
@akirakw
=> Reduce memory usage of `SpillListBuilder`.

vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaSdkBasePlugin.groovy
This PR enables `asakusa-test-windows` module, which enables testing batch applications on Windows, into Asakusa Vanilla testkit.
In release `0.4.0`, the module had been lacked Asakusa Vanilla Gradle plug-ins.
This PR also enables `asakusa-windgate-test-inprocess` module if WindGate feature is enabled.
N/A.
@akirakw
=> Enable `asaksua-test-windows` module into Vanilla testkit.

dag/compiler/builtin/src/main/java/com/asakusafw/dag/compiler/builtin/MasterCheckOperatorGenerator.java, dag/compiler/builtin/src/main/java/com/asakusafw/dag/compiler/builtin/MasterJoinLikeOperatorGenerator.java, dag/compiler/builtin/src/main/java/com/asakusafw/dag/compiler/builtin/MasterJoinOperatorGenerator.java, dag/compiler/builtin/src/test/java/com/asakusafw/dag/compiler/builtin/MasterCheckOperatorGeneratorTest.java, dag/compiler/builtin/src/test/java/com/asakusafw/dag/compiler/builtin/MasterJoinOperatorGeneratorTest.java, dag/compiler/builtin/src/test/java/com/asakusafw/dag/compiler/builtin/MasterJoinUpdateOperatorGeneratorTest.java, dag/compiler/builtin/src/test/java/com/asakusafw/dag/compiler/builtin/MockTable.java
This PR enables `Master{Join,Check}` operators to take extra parameters in Asakusa {on M3BP, Vanilla}.
see asakusafw/asakusafw#708.
N/A.
* asakusafw/asakusafw#708
@akirakw
=> Enable extra parameters on `Master{Join,Check}`.

dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/table/BasicDataTable.java, dag/runtime/runtime/src/test/java/com/asakusafw/dag/runtime/table/BasicDataTableTest.java
This PR revise error messages about type error in `GroupView.find()`.
* before
```
java.lang.IllegalArgumentException: key element at "2" must be type of "class com.asakusafw.runtime.value.IntOption": class java.lang.Integer
at com.asakusafw.dag.runtime.table.BasicDataTable.checkType(BasicDataTable.java:236)
at com.asakusafw.dag.runtime.table.BasicDataTable.find(BasicDataTable.java:176)
...
```
* after
```
java.lang.IllegalArgumentException: key element at 2 is inconsistent type: required=com.asakusafw.runtime.value.IntOption, actual=java.lang.Integer
at com.asakusafw.dag.runtime.table.BasicDataTable.checkType(BasicDataTable.java:236)
at com.asakusafw.dag.runtime.table.BasicDataTable.find(BasicDataTable.java:176)
...
```
N/A.
* #106 
@akirakw
=> Revise error message about type error in `GroupView.find()`.

compiler-project/extension-test-moderator/src/main/java/com/asakusafw/lang/compiler/extension/testdriver/InternalExporterRetriever.java
This PR fixes `InternalExporterRetriever.truncate()` for a corner case. It is used in testkits except Asakusa on MapReduce.
This is similar to asakusafw/asakusafw#705, but this will fail to delete only if the target path does not provides the *parent path*.
N/A.
N/A.
N/A.
=> Fix `InternalExporterRetriever.truncate` for a corner case.

bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/directio/DirectFileInputSplit.java
This PR adds `toString()` method to `DirectFileInputSplit`.
Several platforms will show `DirectFileInputSplit` in their log.
N/A.
N/A.
N/A.
=> Add `DirectFileInputSplit.toString()`.

compiler-project/extension-directio/src/main/java/com/asakusafw/lang/compiler/extension/directio/OutputPattern.java, compiler-project/extension-directio/src/test/java/com/asakusafw/lang/compiler/extension/directio/OutputPatternTest.java, dag/compiler/directio/src/main/java/com/asakusafw/dag/compiler/directio/OutputPatternSerDeGenerator.java, dag/compiler/directio/src/test/java/com/asakusafw/dag/compiler/directio/OutputPatternSerDeGeneratorTest.java, dag/runtime/directio/src/main/java/com/asakusafw/dag/runtime/directio/OutputPatternSerDe.java, dag/runtime/directio/src/test/java/com/asakusafw/dag/runtime/directio/OutputPatternSerDeTest.java
Resource pattern of Direct I/O file output now can accept decimal format (DecimalFormat).
This is asakusafw/asakusafw#719 implementation for Asakusa {on M3BP, Vanilla}.
N/A.
* asakusafw/asakusafw#719
@akirakw
=> Resource pattern of direct output now can accept decimal format.

compiler-project/extension-directio/src/main/java/com/asakusafw/lang/compiler/extension/directio/DirectFileIoPortProcessor.java
This PR fixes error messages in Direct I/O compiler.
The last implementation shows the following message:
```
output resource pattern with wildcards (*) must not contain any orders (<desc-class>.getOrder()): {1}
```
The above `{1}` must be replaced with the actual `.getOrder()` results.
N/A.
N/A.
=> Fix error messages in Direct I/O compiler.

vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/VanillaConfiguration.java, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/VanillaLauncher.java, vanilla/runtime/client/src/test/java/com/asakusafw/vanilla/client/VanillaConfigurationTest.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/BasicBufferStore.java, vanilla/runtime/core/src/test/java/com/asakusafw/vanilla/core/io/BasicBufferStoreTest.java
This PR enables Asakusa Vanilla to divide buffer swap files into individual sub-directories.
The latest implementation, the engine only can put swap files into a single swap directory. It may slow down operations if there are too many files.
This introduces a new engine configuration item (undocumented).
* `com.asakusafw.vanilla.pool.division`
* max swap files in each swap sub-directory, or 0 to disable the feature
* default: `0` (disabled)
N/A.
=> Introduce sub-directory divisions in buffer spilling.

bridge-project/runtime/src/main/java/com/asakusafw/bridge/launch/BatchArgumentsOption.java, bridge-project/runtime/src/main/java/com/asakusafw/bridge/launch/LaunchConfiguration.java, bridge-project/runtime/src/main/java/com/asakusafw/bridge/launch/LaunchInfo.java, dag/runtime/iterative/.gitignore, dag/runtime/iterative/pom.xml, dag/runtime/iterative/src/main/java/com/asakusafw/dag/iterative/DirectLaunchConfiguration.java, dag/runtime/iterative/src/main/java/com/asakusafw/dag/iterative/DirectParameterTableOption.java, dag/runtime/iterative/src/main/java/com/asakusafw/dag/iterative/package-info.java, dag/runtime/pom.xml, iterative-project/launch/src/main/java/com/asakusafw/iterative/launch/IterativeStageInfo.java, vanilla/compiler/core/src/main/java/com/asakusafw/vanilla/compiler/core/VanillaDirectBatchProcessor.java, vanilla/compiler/core/src/main/resources/META-INF/services/com.asakusafw.lang.compiler.api.BatchProcessor, vanilla/compiler/core/src/main/resources/com/asakusafw/vanilla/compiler/core/direct.sh.template, vanilla/runtime/assembly/pom.xml, vanilla/runtime/assembly/src/main/dist/vanilla/bin/execute.sh, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/VanillaDirect.java, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/VanillaLauncher.java
This PR enables DSL compiler for Asakusa Vanilla to generate launcher script for individual jobflows.
N/A.
The launcher scripts will be located on `$ASAKUSA_HOME/batchapps/<batch-id>/bin/<flow-id>.sh`, and they accept batch arguments as "-A name=value" or "-AA /path/to/json".
This feature only generates script for jobflow which consists of only one task, that is, such jobflows only can have Direct I/O or WindGate JDBC direct for its external I/Os.
N/A.
=> DSL compiler for vanilla now generates jobflow launcher.

dag/compiler/builtin/src/main/java/com/asakusafw/dag/compiler/builtin/FoldOperatorGenerator.java, dag/compiler/builtin/src/main/java/com/asakusafw/dag/compiler/builtin/ProjectOperatorGenerator.java, dag/compiler/builtin/src/main/java/com/asakusafw/dag/compiler/builtin/SplitOperatorGenerator.java, dag/compiler/builtin/src/main/java/com/asakusafw/dag/compiler/builtin/SummarizeOperatorGenerator.java, dag/compiler/builtin/src/main/java/com/asakusafw/dag/compiler/builtin/Util.java, dag/compiler/codegen/src/main/java/com/asakusafw/dag/compiler/codegen/AsmUtil.java, dag/compiler/codegen/src/main/java/com/asakusafw/dag/compiler/codegen/BufferOperatorGenerator.java, dag/compiler/codegen/src/main/java/com/asakusafw/dag/compiler/codegen/ExtractAdapterGenerator.java, vanilla/compiler/core/src/test/java/com/asakusafw/vanilla/compiler/core/VanillaJobflowProcessorTest.java
This PR fixes invalid cache reuse of operator adapter classes. 
In the latest implementation, Asakusa {on M3BP, Vanilla} generates invalid operator adapter classes if the operator instance has duplicated outputs (e.g. output to the same operator).
We made operator adapter classes work independently of their outputs.
* asakusafw/asakusafw-dag#38
=> Fix operator adapter class cache conflict.

dag/compiler/builtin/src/main/java/com/asakusafw/dag/compiler/builtin/SummarizeOperatorGenerator.java, dag/compiler/builtin/src/test/java/com/asakusafw/dag/compiler/builtin/SummarizeOperatorGeneratorTest.java, dag/compiler/codegen/src/main/java/com/asakusafw/dag/compiler/codegen/AsmUtil.java
This PR fixes summarize operator behavior that must raise `NullPointerException` if `max/min` target input represented `NULL`.
The latest implementation, `max/min` operations just set `NULL` for `NULL` inputs, but must raise NPE instead in such cases. Asakusa on {on M3BP, Vanilla} only have this problem, and other platforms already work correctly.
In this PR, we check nullity of properties at converting input data models into the corresponded summarized data models. At that time, the implementation will raise NPE for `NULL` inputs with more helpful error messages as like
`MockDataModel.sort must not be null (in Op.simple): {key=100, sort=null, value=Hello, world!}`.
N/A.
=> Raise NPE in summarize operator with MAX/MIN for null values.

dag/runtime/jdbc/src/main/java/com/asakusafw/dag/runtime/jdbc/JdbcProfile.java, dag/runtime/jdbc/src/main/java/com/asakusafw/dag/runtime/jdbc/operation/ConcurrencyLimitter.java, dag/runtime/jdbc/src/main/java/com/asakusafw/dag/runtime/jdbc/operation/JdbcOutputProcessor.java
This PR fixes deadlock in WindGate JDBC direct mode for Asakusa on M3BP (asakusafw/asakusafw-m3bp#81).
In the latest, `com.asakusafw.dag.jdbc.<profile-name>.output.threads` did not work collect. Output worker threads acquire JDBC connection, and sometimes they suspend their work by the scheduler with holding the connection.
We introduced `ConcurrencyLimitter`. It first creates actual `TaskProcessor` instances just as many of `..output.threads`, and borrows it to each worker thread until it was suspended.
* asakusafw/asakusafw-m3bp#81
=> Avoid deadlock in WindGate JDBC direct mode.

dag/compiler/extension-directio/src/test/java/com/asakusafw/dag/compiler/extension/directio/DirectFilePortDriverTest.java, dag/compiler/model/src/main/java/com/asakusafw/dag/compiler/model/build/GraphInfoBuilder.java, dag/compiler/plan/src/main/java/com/asakusafw/dag/compiler/planner/DagPlanning.java
This PR fixes multiple external outputs from the same operator output.
When an operator output is connected to two or more outputs,
```
+--[Output1]
/
.. --[Operator]-+
\
+--[Output2]
```
the DSL compiler will insert vertex bounds in front of the individual outputs.
```
+--[Bound1]--[Output1]
/
.. --[Operator]-+
\
+--[Bound2]--[Output2]
```
These bounds manages shuffle operations of each output, but the consequent optimizer may unify them.
```
+--[Output1]
/
.. --[Operator]--[Bound]-+
\
+--[Output2]
```
This may cause error if each shuffle operations are different at Asakusa {on M3BP, Vanilla} runtime.
```
Exception in thread "main" java.lang.IllegalStateException: ambiguous edges: Port[INPUT](vN:input) ([Edge(SCATTER_GATHER), Edge(SCATTER_GATHER)])
...
at …
```
=> Fix multiple outputs from the same origin.

dag/runtime/api/src/main/java/com/asakusafw/dag/api/processor/basic/BasicTaskSchedule.java, dag/runtime/jdbc/src/conf/findbugs/exclude.xml, dag/runtime/jdbc/src/main/java/com/asakusafw/dag/runtime/jdbc/JdbcInputDriver.java, dag/runtime/jdbc/src/main/java/com/asakusafw/dag/runtime/jdbc/operation/JdbcInputAdapter.java, dag/runtime/jdbc/src/main/java/com/asakusafw/dag/runtime/jdbc/operation/JdbcOutputProcessor.java, dag/runtime/jdbc/src/main/java/com/asakusafw/dag/runtime/jdbc/operation/Util.java, dag/runtime/jdbc/src/main/java/com/asakusafw/dag/runtime/jdbc/oracle/OracleSyntax.java, dag/runtime/jdbc/src/main/java/com/asakusafw/dag/runtime/jdbc/oracle/PartitionedJdbcInputDriver.java, dag/runtime/jdbc/src/main/java/com/asakusafw/dag/runtime/jdbc/oracle/package-info.java, dag/runtime/jdbc/src/main/java/com/asakusafw/dag/runtime/jdbc/util/WindGateJdbcDirect.java, dag/runtime/jdbc/src/test/java/com/asakusafw/dag/runtime/jdbc/operation/JdbcInputAdapterTest.java, dag/runtime/jdbc/src/test/java/com/asakusafw/dag/runtime/jdbc/util/WindGateJdbcDirectTest.java, dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/skeleton/VertexAdapter.java
This PR enables Oracle Database partitions in JDBC direct mode (available in Asakusa {on M3BP, Vanilla}).
In the latest implementation, JDBC direct mode always obtains input data from a table in single-threaded. This PR enables reading individual partitions of a table in parallel.
We have introduced a new optimization option:
* `ORACLE_PARTITION`
* enable partitions for Oracle Databases
* required following settings:
* `com.asakusafw.dag.jdbc.<profile-name>.input.threads` (`> 1`)
* `JdbcImporterDescription.getOptions()`
* `com.asakusafw.dag.jdbc.<profile-name>.optimizations` (append `ORACLE_PARTITION`)
N/A.
=> Support Oracle Database partitions in JDBC direct mode.

dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/data/SpillListBuilder.java, dag/runtime/runtime/src/main/java/com/asakusafw/dag/runtime/skeleton/CoGroupInputAdapter.java, dag/runtime/runtime/src/test/java/com/asakusafw/dag/runtime/data/SpillListBuilderTest.java
This PR enables to configure spill out path of co-group operations with `@Spill` annotation.
In the latest implementation, `@Spill` inputs generate spill-out buffer files onto `java.io.tmpdir` directory. It system temporary directory may be also used in other libraries.
We have introduced a new engine configuration into Asakusa {on M3BP, Vanilla}:
* `com.asakusafw.dag.input.file.directory`
* temporary directory path of spill outputs
* default: N/A (use `java.io.tmpdir`)
N/A.
=> Spill output path is now configurable.

dag/compiler/plan/src/main/java/com/asakusafw/dag/compiler/planner/Util.java, vanilla/compiler/core/src/test/java/com/asakusafw/vanilla/compiler/core/VanillaJobflowProcessorTest.java
This PR fixes views in co-group kind operators (e.g. `@CoGroup`), on DSL compiler for {M3BP, Vanilla}.
If views are appeared in co-group kind operators, DSL compiler will failed with `IllegalStateException`.
```
java.lang.IllegalStateException: null
at com.asakusafw.lang.utils.common.Invariants.require(Invariants.java:78)
at com.asakusafw.lang.utils.common.Invariants.requireNonNull(Invariants.java:41)
at com.asakusafw.dag.compiler.planner.Util.lambda$sortPrimaryInputs$8(Util.java:178)
(snip)
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
at com.asakusafw.dag.compiler.planner.Util.sortPrimaryInputs(Util.java:179)
at com.asakusafw.dag.compiler.planner.Util.sortInputs(Util.java:154)
at com.asakusafw.dag.compiler.planner.Util.computeIds(Util.java:115)
...
```
N/A. …
=> Fix views in co-group kind operators.

vanilla/gradle/build.gradle, vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaSdkPlugin.groovy
This PR replaces uses of Gradle API which will be deprecated since Gradle 4.0.
see asakusafw/asakusafw-sdk#138.
This suppresses warnings on building Asakusa projects with `asakusafw-vanilla` plugin.
* asakusafw/asakusafw-sdk#138
=> Avoid using deprecated methods since Gradle 4.0.

compiler-project/extension-windgate/src/main/java/com/asakusafw/lang/compiler/extension/windgate/info/WindGateIoAttributeCollector.java, compiler-project/extension-windgate/src/main/java/com/asakusafw/lang/compiler/extension/windgate/info/package-info.java, compiler-project/extension-windgate/src/main/resources/META-INF/services/com.asakusafw.lang.info.api.AttributeCollector, info/pom.xml, info/windgate/.gitignore, info/windgate/pom.xml, info/windgate/src/main/java/com/asakusafw/lang/info/windgate/Util.java, info/windgate/src/main/java/com/asakusafw/lang/info/windgate/WindGateInputInfo.java, info/windgate/src/main/java/com/asakusafw/lang/info/windgate/WindGateIoAttribute.java, info/windgate/src/main/java/com/asakusafw/lang/info/windgate/WindGateOutputInfo.java, info/windgate/src/main/java/com/asakusafw/lang/info/windgate/WindGatePortInfo.java, info/windgate/src/main/java/com/asakusafw/lang/info/windgate/package-info.java, info/windgate/src/test/java/com/asakusafw/lang/info/windgate/WindGateInputInfoTest.java, info/windgate/src/test/java/com/asakusafw/lang/info/windgate/WindGateIoAttributeTest.java, info/windgate/src/test/java/com/asakusafw/lang/info/windgate/WindGateOutputInfoTest.java
This PR enables to add WindGate information into `etc/batch-info.json`.
N/A.
This is enhancement of #113 to for WindGate.
The following `jq` command line is an example of extracting WindGate I/O information from `etc/batch-info.json`:
```
jq '.jobflows[].attributes[] | select(.id == "windgate")'
```
Note that, this feature is only enabled in Gradle if `asakusafw.sdk.incubating` is `true`.
* #113
=> Add WindGate information into `etc/batch-info.json`.

compiler-project/analyzer/src/main/java/com/asakusafw/lang/compiler/analyzer/FlowGraphAnalyzer.java
This PR fixes treating `stop` operators as ineffective `checkpoint` operators.
In the latest implementation, the DSL compiler sometimes converts `stop` operators into `checkpoint` operators. Either way, the compiler will remove them.
Note that, DSL information viewer, which has been introduced in #134, can display such ineffective `checkpoint` operators.
N/A.
N/A.
=> Fix treating `stop` operators as ineffective `checkpoint`.

dag/compiler/flow/src/main/java/com/asakusafw/dag/compiler/flow/DataFlowGenerator.java
This PR fixes generating execution plan information in {on M3BP, Vanilla}.
The latest implementation sometimes generates wrong I/O port name for vertices, and it may raise NPE at the viewer tool introduced in #134.
N/A.
* #134
=> Fix I/O port name for exec plan information.

compiler-project/extension-info/src/main/java/com/asakusafw/lang/compiler/extension/info/BatchInfoParticipant.java, compiler-project/extension-info/src/main/java/com/asakusafw/lang/compiler/extension/info/TaskListAttributeCollector.java, compiler-project/extension-info/src/main/resources/META-INF/services/com.asakusafw.lang.info.api.AttributeCollector, compiler-project/extension-operator/src/main/java/com/asakusafw/lang/compiler/operator/info/PlanAttributeStore.java, dag/compiler/flow/src/main/java/com/asakusafw/dag/compiler/flow/DataFlowGenerator.java, info/api/src/main/java/com/asakusafw/lang/info/api/AttributeCollector.java, info/cli/src/main/java/com/asakusafw/lang/info/cli/DrawCommand.java, info/cli/src/main/java/com/asakusafw/lang/info/cli/DrawEngine.java, info/cli/src/main/java/com/asakusafw/lang/info/cli/DrawJobflowCommand.java, info/cli/src/main/java/com/asakusafw/lang/info/cli/DrawOperatorCommand.java, info/cli/src/main/java/com/asakusafw/lang/info/cli/DrawPlanCommand.java, info/cli/src/main/java/com/asakusafw/lang/info/cli/Drawer.java, info/cli/src/main/java/com/asakusafw/lang/info/cli/ListJobflowCommand.java, info/model/src/main/java/com/asakusafw/lang/info/plan/PlanOutputSpec.java, info/model/src/main/java/com/asakusafw/lang/info/task/TaskInfo.java, info/model/src/main/java/com/asakusafw/lang/info/task/TaskListAttribute.java, info/model/src/main/java/com/asakusafw/lang/info/task/package-info.java, info/model/src/test/java/com/asakusafw/lang/info/task/TaskListAttributeTest.java
This PR adds task graph information into `batch-info.json`.
`batch-info.json` file has been introduced as incubating feature (`asakusafw.sdk.incubating = true`) since #113. This additionally enables task graph information for Asakusa {on Spark, M3BP, Vanilla}.
This also enables to display task information by using information viewer (`info/cli`):
* `list jobflow -v`
* `draw jobflow --show-task`
* #113
=> Add task graph information into `batch-info.json`.

bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/combine/CombinedInputSplit.java, bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/combine/CombinedRecordReader.java, bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/combine/DefaultSplitCombiner.java, bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/combine/SplitCombiner.java, bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/combine/package-info.java, bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/directio/DirectFileInputFormat.java, bridge-project/runtime-hadoop/src/test/java/com/asakusafw/bridge/hadoop/directio/DirectFileInputFormatTest.java
This PR enables to combine input splits of Direct I/O (for Asakusa on Spark).
Asakusa on Spark sometimes fails if there are large number of input files in a single jobflow. This feature combines a large number of input files into a several input splits.
To enable this feature, please put the following into `asakusa-resources.xml`:
* `com.asakusafw.bridge.directio.input.combine=N`
* max number of input splits for each Direct I/O input
* default: `-1` (disabled)
N/A.
=> Enable combining input split of Direct I/O.

info/cli/src/main/dist/tools/bin/info.sh, info/cli/src/main/java/com/asakusafw/lang/info/cli/Info.java
This PR enables `$ASAKUSA_HOME/tools/bin/info.sh` to display correct command name of itself in the help message.
In the latest implementation the command `$ASAKUSA_HOME/tools/bin/info.sh` shows a help message like:
```
usage: java -jar asakusa-info.jar <command> [<args>]
The most commonly used java -jar asakusa-info.jar commands are:
draw   Generates Graphviz DOT scripts
help   Display help information
list   Displays information list
See 'java -jar asakusa-info.jar help <command>' for more information on a
specific command.
```
We improved the above message into:
```
usage: info.sh <command> [<args>]
The most commonly used info.sh commands are:
draw   Generates Graphviz DOT scripts
help   Display help information
list   Displays information list
See 'info.sh help <command>' for more …
```
=> Display correct command name of `tools/bin/info.sh`.

vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaSdkBasePlugin.groovy, vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaTestkit.groovy, vanilla/gradle/src/main/resources/META-INF/services/com.asakusafw.gradle.plugins.AsakusafwSdkPluginParticipant, vanilla/gradle/src/test/groovy/com/asakusafw/vanilla/gradle/plugins/AsakusaPluginParticipantTest.groovy
This PR enables Asakusa Vanilla testkit in default if `asakusafw.sdk.incubating true`.
In the latest implementation, Asakusa on MapReduce is used as the default testkit. We make Vanilla default testkit if `incubating=true`. It is also available even if `apply plugin: 'asakusafw-vanilla'` does not exist in `build.gradle`. Note that, Asakusa on MapReduce testkit is still available in default if if `incubating=false`.
N/A.
N/A.
=> Enable vanilla testkit instead of mapreduce if `incubating true`.

integration/build.gradle
This PR fixed lack of repository definition for integration test (#145).
N/A.
Add repository definition to `integration/build.gradle`
#145
=> Fix lack of repository definition for integration test

vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaTestkit.groovy
This PR makes Asakusa Vanilla as default testkit instead of MapReduce.
Asakusa Vanilla testkit has been enabled in #144 only if `asakusafw.sdk.incubating true`, otherwise enabled MapReduce testkit. This PR enables the Vanilla testkit even if `asakusafw.sdk.incubating true` is not specified.
The latest `AsakusaVanillaTestkit.priority` was `10` on `incubating=false`, or `1,000` on `incubating=true` by contrast the MapReduce testkit has `100`. We fixed the prority of Vanilla testkit to `200`, and MapReduce testkit to `1` (in asakusafw/asakusafw-mapreduce#11), then the Vanilla testkit will be always enabled from here.
* #144
* asakusafw/asakusafw-mapreduce#11
=> Promote Asakusa Vanilla as the default testkit.

integration/src/integration-test/java/com/asakusafw/integration/lang/PortalTest.java
This PR fixes an integration test case which has been failed since #154.
#154 introduced an invalid test case that invokes a command `asakusa hive`. It should be `asakusa list hive`.
N/A.
* #154
=> Fix integration test.

compiler-project/extension-windgate/src/main/java/com/asakusafw/lang/compiler/extension/windgate/WindGatePortProcessor.java, compiler-project/tester/src/main/java/com/asakusafw/lang/compiler/tester/executor/HadoopTaskExecutor.java, dag/runtime/extension/windows/.gitignore, dag/runtime/extension/windows/pom.xml, dag/runtime/extension/windows/src/main/java/com/asakusafw/dag/extension/windows/WindowsSupportExtension.java, dag/runtime/extension/windows/src/main/java/com/asakusafw/dag/extension/windows/package-info.java, dag/runtime/extension/windows/src/main/resources/META-INF/services/com.asakusafw.dag.api.processor.extension.ProcessorContextExtension, dag/runtime/pom.xml, vanilla/compiler/common/src/main/java/com/asakusafw/vanilla/compiler/common/VanillaTask.java, vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaOrganizer.groovy, vanilla/runtime/assembly/.gitattributes, vanilla/runtime/assembly/src/main/dist/vanilla/bin/execute, vanilla/runtime/bootstrap/.gitignore, vanilla/runtime/bootstrap/pom.xml, vanilla/runtime/bootstrap/src/main/assembly/dist.xml, vanilla/runtime/bootstrap/src/main/dist/vanilla/bin/execute.cmd, vanilla/runtime/bootstrap/src/main/java/com/asakusafw/vanilla/bootstrap/Arguments.java, vanilla/runtime/bootstrap/src/main/java/com/asakusafw/vanilla/bootstrap/Classpath.java, vanilla/runtime/bootstrap/src/main/java/com/asakusafw/vanilla/bootstrap/ConfigurationException.java, vanilla/runtime/bootstrap/src/main/java/com/asakusafw/vanilla/bootstrap/Context.java, vanilla/runtime/bootstrap/src/main/java/com/asakusafw/vanilla/bootstrap/CoreConstants.java, vanilla/runtime/bootstrap/src/main/java/com/asakusafw/vanilla/bootstrap/Environment.java, vanilla/runtime/bootstrap/src/main/java/com/asakusafw/vanilla/bootstrap/ExecutionException.java, vanilla/runtime/bootstrap/src/main/java/com/asakusafw/vanilla/bootstrap/VanillaBootstrap.java, vanilla/runtime/bootstrap/src/main/java/com/asakusafw/vanilla/bootstrap/VanillaConstants.java, vanilla/runtime/bootstrap/src/main/java/com/asakusafw/vanilla/bootstrap/package-info.java, vanilla/runtime/pom.xml
This PR enables `asakusa run` command to execute batch applications on Windows platform.
see asakusafw/asakusafw#752.
This includes the following changes:
* remove `.sh` extension from Vanilla command (`vanilla/bin/execute.sh`)
* add `vanilla/bin/execute.cmd`
* fix for upstream change which renames WindGate commands
* asakusafw/asakusafw#752
=> `asakusa run` on Windows.

vanilla/runtime/assembly/src/main/dist/vanilla/bin/execute, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/VanillaConstants.java, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/VanillaDirect.java, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/VanillaLauncher.java
This PR revises Asakusa on Vanilla log messages.
N/A.
We removed messages in launcher shell script before launching Vanilla Java application, and then displays some environment variables as debug level log messages.
N/A.
=> Revise Vanilla log messages.

vanilla/gradle/src/test/groovy/com/asakusafw/vanilla/gradle/plugins/AsakusaUpgradeTest.groovy
This PR adds unit test for upstream change of Gradle version (asakusafw/asakusafw#759).
See asakusafw/asakusafw#759.
N/A.
* asakusafw/asakusafw#759
=> Add test of `asakusaUpgrade` with Gradle 4.1.

gradle/build.gradle, vanilla/gradle/build.gradle
This PR bumps Gradle required JDK version to `1.8`.
See asakusafw/asakusafw#760.
N/A.
* See asakusafw/asakusafw#760.
=> Bump Gradle required Java version to 1.8.

compiler-project/extension-windgate/src/main/java/com/asakusafw/lang/compiler/extension/windgate/DescriptionModel.java, compiler-project/extension-windgate/src/test/java/com/asakusafw/lang/compiler/extension/windgate/WindGatePortProcessorTest.java
This PR fixes bug of missing parameter information of WindGate I/O.
`asakusa list parameter` does not show implicitly referred parameters in WindGate.
N/A.
N/A.
=> Keep parameter names of WindGate vocabularies.

bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/temporary/TemporaryFileInputFormat.java, bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/temporary/TemporaryFileOutputFormat.java, bridge-project/runtime-hadoop/src/main/java/com/asakusafw/bridge/hadoop/temporary/package-info.java, bridge-project/runtime-hadoop/src/test/java/com/asakusafw/bridge/hadoop/temporary/TemporaryFileInputFormatTest.java, bridge-project/runtime-hadoop/src/test/java/com/asakusafw/bridge/hadoop/temporary/TemporaryFileOutputFormatTest.java, compiler-project/extension-test-moderator/pom.xml, compiler-project/mapreduce-testing/src/main/java/com/asakusafw/lang/compiler/mapreduce/testing/InputFormatTester.java, compiler-project/mapreduce-testing/src/main/java/com/asakusafw/lang/compiler/mapreduce/testing/OutputFormatTester.java, compiler-project/test-adapter/pom.xml
This PR introduces `TemporaryFile{Input,Output}Format` which are alternatives of `Temporary{Input,Output}Format`. These are inherit standard `File{Input,Output}Format` for newer Spark runtimes.
The existing `Temporary{Input,Output}Format` does not work correct on Spark `>= 2.2`. It seems that the Spark requires each input/output format inherits standard `File{Input,Output}Format`. Then we have introduced `TemporaryFile{Input,Output}Format`. These are almost compatible the existing format pair, but the introduced may not work with MapReduce `Multiple{Inputs,Outputs}` correctly.
N/A.
N/A.
=> Introduce `TemporaryFile{Input,Output}Format`.

vanilla/gradle/src/main/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaOrganizerPlugin.groovy, vanilla/gradle/src/test/groovy/com/asakusafw/vanilla/gradle/plugins/internal/AsakusaVanillaOrganizerPluginTest.groovy
This PR enables Asakusa Vanilla organizer even if `asakusafwOrganizer.vanilla.enabled true` was not set.
The latest implementation, enabling Asakusa Vanilla applications was required two steps:
1. `apply: 'asakusafw-vanilla'`
2. `asakusafwOrganizer.vanilla.enabled true`
It is because the Asakusa Vanilla testkit had been required the above first step, but the testkit was enabled without the first step in the latest version (`0.10.0`).
This PR removes the second step to obtain the Asakusa Vanilla applications, and change the default value of `asakusafwOrganizer.vanilla.enabled` to `true`.
N/A.
N/A.
=> Asakusa Vanilla organizer should be enabled in default.

compiler-project/test-adapter/src/main/java/com/asakusafw/lang/compiler/testdriver/adapter/CompilerSessionAdapter.java, compiler-project/test-adapter/src/test/java/com/asakusafw/lang/compiler/testdriver/adapter/CompilerToolkitAdapterTest.java
This PR revises error messages of `FlowPartTester` when invalid `In` / `Out` objects are passed to flow classes.
In the latest implementation, `FlowPartTester` accepts `In`/`Out` objects without importer/exporter information (e.g. `Mock{In,Out}`), and they would crash subsequent operations in the compiler.
This PR adds early check whether each I/O port has valid importer/exporter information or raise an error before compiling.
N/A.
=> Revise error message if FPTester got invalid I/O ports.

compiler-project/analyzer/src/main/java/com/asakusafw/lang/compiler/analyzer/FlowGraphVerifier.java
This PR enables `Connectivity` attribute for individual output ports. It suppresses errors that an output port does not connect to any opposites.
Generally, all output ports of operators must be connected to other operators' input ports, but operators with `Connectivity.OPTIONAL` can have outputs without any opposites.
This commit also enables their output ports to have `Connectivity` attributes.
N/A.
* asakusafw/asakusafw#801
=> Enable `Connectivity` option for operator output ports.

compiler-project/test-adapter/src/main/java/com/asakusafw/lang/compiler/testdriver/adapter/CompilerSessionAdapter.java
This PR fixes `FlowPartTester` which should check operator graph invariant (e.g. each output port should connects to opposites).
`FlowPartTester` does not invoke `FlowGraphVerifier` which verifies `FlowGraph` invariants. Note that, `JobflowTester` and `BatchTester` checks correctly.
N/A.
N/A.
=> Check operator graph invariant in FlowPartTester.

compiler-project/model/src/main/java/com/asakusafw/lang/compiler/model/graph/AttributeMap.java
This PR fixes `NullPointerException` on building master-join like operator with views.
The latest implementation, the compiler cannot build master-join like operators (e.g. `MasterJoinUpdate`) if it has views and performs hash-based join.
N/A.
* asakusafw/asakusafw#815
=> Fix NPE on building master-join like operators with views.

compiler-project/common/src/main/java/com/asakusafw/lang/compiler/common/Adaptable.java, compiler-project/common/src/main/java/com/asakusafw/lang/compiler/common/Adaptables.java, compiler-project/common/src/main/java/com/asakusafw/lang/compiler/common/BasicDiagnostic.java, compiler-project/common/src/main/java/com/asakusafw/lang/compiler/common/Diagnostic.java, compiler-project/common/src/main/java/com/asakusafw/lang/compiler/common/DiagnosticException.java, compiler-project/inspection/src/main/java/com/asakusafw/lang/compiler/inspection/AbstractInspectionExtension.java, compiler-project/inspection/src/main/java/com/asakusafw/lang/compiler/inspection/InspectionExtension.java, compiler-project/inspection/src/test/java/com/asakusafw/lang/compiler/inspection/InspectionExtensionTest.java, compiler-project/model/src/main/java/com/asakusafw/lang/compiler/model/graph/Operators.java, compiler-project/plan/src/main/java/com/asakusafw/lang/compiler/planning/PlanDetail.java, compiler-project/plan/src/main/java/com/asakusafw/lang/compiler/planning/Planning.java, compiler-project/plan/src/main/java/com/asakusafw/lang/compiler/planning/basic/BasicPlan.java, dag/compiler/plan/src/main/java/com/asakusafw/dag/compiler/planner/DagPlanning.java, dag/compiler/plan/src/main/java/com/asakusafw/dag/compiler/planner/PlanningContext.java, dag/compiler/plan/src/test/java/com/asakusafw/dag/compiler/planner/DagPlanningTest.java, vanilla/compiler/core/src/main/java/com/asakusafw/vanilla/compiler/core/VanillaJobflowProcessor.java, vanilla/compiler/core/src/test/java/com/asakusafw/vanilla/compiler/core/VanillaJobflowProcessorTest.java
This PR fixes compilation error that some broadcast operations will organize cyclic dependencies.
Broadcast operations (e.g. views, join with TINY input) sometimes had organized invalid cyclic dependencies.
This PR will resolve this problem by introducing extra checkpoints in front of operators which directly consume the (potentially) problematic broadcast inputs.
This feature is currently experimental but **enabled in default**.
To disable this feature, please specify a compiler property `dag.planning.option.removeCyclicBroadcasts=false` in your build script.
N/A.
=> Avoid cyclic dependencies between broadcasts.

vanilla/runtime/assembly/pom.xml
This PR adds more vanilla default extensions to vanilla runtime assembly.
This PR enables vanilla runtime extension features useful for debugging and tracing.
You can use the following vanilla runtime configuration properties:
* `com.asakusafw.dag.extension.trace`
This option enables to report vanilla runtime trace infomation via Report API. Currently this is only enables to specify `com.asakusafw.dag.extension.trace.PortDigester` that reports digests of each port I/O.
```
com.asakusafw.dag.extension.trace=com.asakusafw.dag.extension.trace.PortDigester
```
* `com.asakusafw.dag.extension.wait.before` , `com.asakusafw.dag.extension.wait.after`
This option specifies to wait time (msec) around DAG executions. For example this is useful for attaching or detaching remote debug connection.
``` …
```
=> Add extension for default vanilla assembly

vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/VanillaConfiguration.java, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/VanillaLauncher.java, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/util/SnappyByteChannelDecorator.java, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/util/package-info.java, vanilla/runtime/client/src/test/java/com/asakusafw/vanilla/client/VanillaConfigurationTest.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/engine/BasicEdgeDriver.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/engine/VertexExecutor.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/BasicBufferStore.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/BasicKeyValueSink.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/BlobStore.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/BufferedByteChannelDecorator.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/ByteChannelDecorator.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/ByteChannelReader.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/ByteChannelWriter.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/DataWriter.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/NullByteChannelDecorator.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/StreamGroupWriter.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/StreamObjectWriter.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/Util.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/mirror/MockDataChannel.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/util/BufferedReadbleByteChannel.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/util/BufferedWritableByteChannel.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/util/Buffers.java, vanilla/runtime/core/src/test/java/com/asakusafw/vanilla/core/engine/BasicEdgeDriverTest.java, vanilla/runtime/core/src/test/java/com/asakusafw/vanilla/core/io/BasicBufferStoreTest.java, vanilla/runtime/core/src/test/java/com/asakusafw/vanilla/core/io/BasicKeyValueSinkTest.java, vanilla/runtime/core/src/test/java/com/asakusafw/vanilla/core/io/ByteChannelWriterTest.java, vanilla/runtime/core/src/test/java/com/asakusafw/vanilla/core/io/MockByteChannelDecorator.java, vanilla/runtime/core/src/test/java/com/asakusafw/vanilla/core/util/BufferedReadbleByteChannelTest.java, vanilla/runtime/core/src/test/java/com/asakusafw/vanilla/core/util/BufferedWritableByteChannelTest.java
This PR revises buffer spilling mechanism in Asakusa Vanilla.
This introduces the following features:
* spill files compression
* improve spill file I/O
* multiple stage merging (on scatter/gather)
The series of commits in this PR introduce the following configurations (as Asakusa Vanilla engine configurations):
* `com.asakusafw.vanilla.merge.threshold`
* the maximum number of merging scatter/gather input chunks at one time per thread
* default: `0` (disable multi stage merging)
* `com.asakusafw.vanilla.merge.factor`
* if the scatter/gather input chunks are exceeded, the engine will decide the number of target files at the rate of the above threshold
* default: `1.0` (merge the same number of `com.asakusafw.vanilla.merge.threshold`)
* `com.asakusafw.vanilla.pool.compression`
* a decorator …
=> revise Vanilla buffer spilling.

pom.xml, vanilla/runtime/client/pom.xml, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/VanillaConfiguration.java, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/VanillaLauncher.java, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/util/Lz4ByteChannelDecorator.java, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/util/Lz4FramedReadableByteChannel.java, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/util/Lz4FramedWritableByteChannel.java, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/util/Lz4Util.java, vanilla/runtime/client/src/test/java/com/asakusafw/vanilla/client/VanillaConfigurationTest.java, vanilla/runtime/client/src/test/java/com/asakusafw/vanilla/client/util/Lz4ByteChannelDecoratorTest.java, vanilla/runtime/client/src/test/java/com/asakusafw/vanilla/client/util/Lz4FramedWritableByteChannelTest.java, vanilla/runtime/client/src/test/java/com/asakusafw/vanilla/client/util/SnappyByteChannelDecoratorTest.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/ByteBufferReader.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/ByteChannelDecorator.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/util/BufferedReadbleByteChannel.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/util/BufferedWritableByteChannel.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/util/Buffers.java
This PR enables Asakusa Vanilla buffer spill compression to use LZ4.
This PR introduces a new buffer spill files compression engine. It splits each buffer spill into small frames, and then compresses them using LZ4 compressor.
The base mechanism has been introduced #192, but it only includes Snappy compression.
To enable this feature, please pass the following engine configuration to Asakusa Vanilla:
* `com.asakusafw.vanilla.pool.compression=com.asakusafw.vanilla.client.util.Lz4ByteChannelDecorator`
and then the put the [lz4-java](https://github.com/lz4/lz4-java) into classpath of Asakusa Vanilla, for example:
```gradle
configurations {
lz4
}
dependencies {
lz4 group: 'org.lz4', name: 'lz4-java', version: '1.5.1'
}
asakusafwOrganizer {
assembly.into('vanilla/lib') {
put configurations.lz4 …
```
=> enable buffer spill compression with LZ4 in Asakusa Vanilla.

vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/util/SnappyByteChannelDecorator.java
This PR makes `SnappyByteChannelDecorator` more configurable.
This introduces some configuration properties into  `SnappyByteChannelDecorator` since #192, like as following:
* frame size (like as #193)
* required compression ratio
* input verifying
To configure each internal behavior, please configure the following **system properties**:
* `com.asakusafw.vanilla.snappy.frame.size`
* snappy compression frame size in bytes
* this must be `[4096, 65536]`
* default: `65536` (64KB)
* `com.asakusafw.vanilla.snappy.frame.compressionThreshold`
* required minimum compression ratio for each frame
* If a (`compressed-size` / `original-size`) was exceeded, this will store the uncompressed data instead of compressed one
* default: `0.85` (require 15% size saved)
* …
=> make `SnappyByteChannelDecorator` more configurable.

vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/VanillaConfiguration.java
This PR revises the default configuration of multiple stage merge factor in Asakusa Vanilla.
In #192, multiple stage merging often merges wastefully huge files in default settings. This PR will reduce this problem.
* `com.asakusafw.vanilla.merge.factor`
* if the scatter/gather input chunks are exceeded, the engine will decide the number of target files at the rate of the above threshold
* default: `{1.0=>0.75}` (merge `75%` of `com.asakusafw.vanilla.merge.threshold`)
Note that, this may improve performance until intermediate data size (for each thread) of scatter/gather operation:
```
intermediate-data-size < (buffer-size - buffer-margin) * merge-threshold * (1.0 - merge-factor)
where
buffer-size = conf: com.asakusafw.vanilla.output.buffer.size,
buffer-margin = conf: …
```
=> change default multi-stage merge factor to `0.75` in Vanilla.

vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/util/SnappyByteChannelDecorator.java, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/util/SnappyFramedReadableByteChannel.java, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/util/SnappyFramedWritableByteChannel.java, vanilla/runtime/client/src/main/java/com/asakusafw/vanilla/client/util/SnappyUtil.java, vanilla/runtime/client/src/test/java/com/asakusafw/vanilla/client/util/SnappyFramedWritableByteChannelTest.java
This PR replaces implementation of `SnappyByteChannelDecorator`, and removes some configuration parameters introduced in #194.
This include the following features:
* improve memory usage
* optimize for off-heap buffers
To enable this feature, please put the following engine configuration:
* `com.asakusafw.vanilla.pool.compression=com.asakusafw.vanilla.client.util.SnappyByteChannelDecorator`
To configure each internal behavior, please configure
the following **system properties**:
* `com.asakusafw.vanilla.snappy.frame.size`
* system property key of compression frame size in bytes
* default: `16384` (16KB)
Note that, the legacy internal configurations (for internal behavior) are superseded by this commit.
* #194
=> replace implementation of `SnappyByteChannelDecorator`.

vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/engine/BasicEdgeDriver.java, vanilla/runtime/core/src/main/java/com/asakusafw/vanilla/core/io/BasicKeyValueSink.java, vanilla/runtime/core/src/test/java/com/asakusafw/vanilla/core/engine/BasicEdgeDriverTest.java
This PR fixes wrong shuffle operation in Vanilla, since #192.
N/A.
N/A.
* #192
=> fix wrong shuffle operation in Vanilla.

integration/README.md, integration/src/integration-test/data/ksv-hive/src/main/dmdl/hive.dmdl, integration/src/integration-test/data/ksv-hive/src/main/java/com/example/hive/CsvInputDescription.java, integration/src/integration-test/data/ksv-hive/src/main/java/com/example/hive/CsvOutputDescription.java, integration/src/integration-test/data/ksv-hive/src/main/java/com/example/hive/CsvToOrcJob.java, integration/src/integration-test/data/ksv-hive/src/main/java/com/example/hive/CsvToParquetJob.java, integration/src/integration-test/data/ksv-hive/src/main/java/com/example/hive/OrcIoBatch.java, integration/src/integration-test/data/ksv-hive/src/main/java/com/example/hive/OrcToCsvJob.java, integration/src/integration-test/data/ksv-hive/src/main/java/com/example/hive/ParquetIoBatch.java, integration/src/integration-test/data/ksv-hive/src/main/java/com/example/hive/ParquetToCsvJob.java, integration/src/integration-test/data/vanilla/build.gradle, integration/src/integration-test/java/com/asakusafw/integration/lang/HiveTest.java, integration/src/integration-test/java/com/asakusafw/integration/lang/PortalTest.java
This PR introduces more integration test cases about asakusafw/asakusafw#834, which enables to use `hive-exec:2.3.4`.
N/A.
N/A.
* asakusafw/asakusafw#834
=> add more integration test about Direct I/O Hive.

bridge-project/runtime-directio/src/main/java/com/asakusafw/bridge/directio/api/DirectIo.java, bridge-project/runtime-directio/src/main/java/com/asakusafw/bridge/directio/api/activate/DirectIoApiActivator.java, bridge-project/runtime/src/main/java/com/asakusafw/bridge/api/BatchContext.java, bridge-project/runtime/src/main/java/com/asakusafw/bridge/api/Report.java, bridge-project/runtime/src/main/java/com/asakusafw/bridge/api/activate/BatchContextApiActivator.java, bridge-project/runtime/src/main/java/com/asakusafw/bridge/api/activate/ReportApiActivator.java
This PR marks framework API classes in `asakusafw-bridge-runtime` as deprecated.
Framework API classes in `asakusafw-bridge-runtime` are same name in `asakusa-runtime`. It sometimes confuses when using Eclipse.
N/A.
N/A.
=> mark deprecated to framework API classes in bridge.

compiler-project/api/src/main/java/com/asakusafw/lang/compiler/api/CompilerOptions.java, compiler-project/core/src/main/java/com/asakusafw/lang/compiler/core/participant/JavaSourceExtensionParticipant.java, compiler-project/javac/src/main/java/com/asakusafw/lang/compiler/javac/JavaCompilerUtil.java, compiler-project/javac/src/test/java/com/asakusafw/lang/compiler/javac/JavaCompilerUtilTest.java
This PR enables DSL compiler to extract `Class-Path` entries in each JAR manifest.
This feature is mainly to support running tests with Eclipse Buildship environment.
Additionally, this PR introduces a way to inject DSL compiler options via system properties.
The introduced feature is currently **DISABLED** by default, please add compiler option `javac.classpath.manifest=true` to enable it, or specify `-Dasakusafw.lang.javac.classpath.manifest=true` to launching JVM arguments.
This introduces the following compiler option:
* `javac.classpath.manifest`
* whether or not jobflow compiler treat `Class-Path` entry in manifest file of each class library on compiling generated source files
* default: `false` (disabled)
* `javac.classpath.extension`
* whether or not jobflow compiler treat Java …
=> DSL compiler supports `Class-Path` entries in each JAR manifest.

.github/CONTRIBUTING.md, gradle/build.gradle, integration/build.gradle, integration/src/integration-test/data/vanilla/build.gradle, pom.xml, vanilla/gradle/build.gradle
This PR changes maven repository URL protocol from http to https in `pom.xml` and `build.gradle` for framework build configurations.
This also changes link URL to https in documentation files.
Follow-up asakusafw/asakusafw#845
The same as asakusafw/asakusafw#845
N/A.
=> Change maven repository URL to use https in build configurations
